import type { TransactionSql } from "postgres";
import type { TenantContext } from "@/lib/tenancy";
import { authorize } from "@/features/tenant-identity/authorize";
import { DEFAULT_MAX_JOB_ATTEMPTS } from "@/lib/jobs";

export type MinimalNotificationPayload={appointmentId?:string;siteId?:string;event:"reminder"|"booking"|"reschedule"|"cancellation";startsAt?:string};
export async function scheduleEmailNotification(sql:TransactionSql,actor:TenantContext,input:{appointmentId?:string;recipient?:string|null;emailConsent:boolean;kind:MinimalNotificationPayload["event"];dueAt:Date;siteId?:string;startsAt?:Date}):Promise<{id:string|null;state:"pending"|"cancelled";reason?:string}>{authorize(actor,"communication:manage");const payload:MinimalNotificationPayload={appointmentId:input.appointmentId,siteId:input.siteId,event:input.kind,startsAt:input.startsAt?.toISOString()};if(!input.emailConsent||!input.recipient||!/^\S+@\S+\.\S+$/.test(input.recipient)){const row=(await sql<{id:string}[]>`INSERT INTO notifications (organization_id,appointment_id,channel,recipient,consent_verified,kind,due_at,state,payload,created_by_membership_id) VALUES (${actor.organizationId},${input.appointmentId??null},'email',${input.recipient??"withheld"},false,${input.kind},${input.dueAt},'cancelled',${JSON.stringify(payload)}::jsonb,${actor.membershipId}) ON CONFLICT (organization_id,appointment_id,kind,channel,due_at) DO NOTHING RETURNING id`)[0];return{id:row?.id??null,state:"cancelled",reason:"missing_consent_or_address"};}const row=(await sql<{id:string;state:"pending"|"cancelled"}[]>`INSERT INTO notifications (organization_id,appointment_id,channel,recipient,consent_verified,kind,due_at,payload,created_by_membership_id) VALUES (${actor.organizationId},${input.appointmentId??null},'email',${input.recipient},true,${input.kind},${input.dueAt},${JSON.stringify(payload)}::jsonb,${actor.membershipId}) ON CONFLICT (organization_id,appointment_id,kind,channel,due_at) DO UPDATE SET updated_at=notifications.updated_at RETURNING id,state`)[0]!;return row;}

export type DeliveryResult={outcome:"sent"|"failed";providerReference?:string;errorCode?:string};
type DeliveryMessage={to:string;payload:MinimalNotificationPayload;idempotencyKey:string};
async function boundedDelivery(deliver:(message:DeliveryMessage)=>Promise<DeliveryResult>,message:DeliveryMessage,timeoutMs:number):Promise<DeliveryResult>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([deliver(message),new Promise<DeliveryResult>(resolve=>{timer=setTimeout(()=>resolve({outcome:"failed",errorCode:"provider_timeout"}),timeoutMs);})]);}catch{return{outcome:"failed",errorCode:"provider_error"};}finally{if(timer)clearTimeout(timer);}}
export async function deliverDueNotifications(sql:TransactionSql,actor:TenantContext,deliver:(message:DeliveryMessage)=>Promise<DeliveryResult>,now=new Date(),timeoutMs=10000):Promise<{processed:number}>{authorize(actor,"communication:manage");const due=await sql<Array<{id:string;recipient:string;payload:MinimalNotificationPayload;sequence:number}>>`SELECT n.id,n.recipient,n.payload,(SELECT COALESCE(MAX(a.sequence::integer),0)+1 FROM notification_attempts a WHERE a.notification_id=n.id AND a.organization_id=n.organization_id) AS sequence FROM notifications n WHERE n.organization_id=${actor.organizationId} AND n.channel='email' AND n.state='pending' AND n.consent_verified AND n.due_at<=${now} FOR UPDATE OF n SKIP LOCKED`;let processed=0;for(const item of due){const claimed=await sql`UPDATE notifications SET state='processing',updated_at=now() WHERE organization_id=${actor.organizationId} AND id=${item.id} AND state='pending'`;if(claimed.count!==1)continue;const result=await boundedDelivery(deliver,{to:item.recipient,payload:item.payload,idempotencyKey:item.id},timeoutMs);await sql`INSERT INTO notification_attempts (organization_id,notification_id,sequence,outcome,provider_reference,error_code) VALUES (${actor.organizationId},${item.id},${String(item.sequence)},${result.outcome},${result.providerReference??null},${result.errorCode??null})`;await sql`UPDATE notifications SET state=${result.outcome},updated_at=now() WHERE organization_id=${actor.organizationId} AND id=${item.id} AND state='processing'`;processed++;}return{processed};}

export async function retryFailedNotification(sql:TransactionSql,actor:TenantContext,notificationId:string,maxAttempts=DEFAULT_MAX_JOB_ATTEMPTS):Promise<boolean>{authorize(actor,"communication:manage");const safeBound=Number(maxAttempts);if(!Number.isSafeInteger(safeBound)||safeBound<1||safeBound>10)throw new Error("Invalid retry bound.");const result=await sql`UPDATE notifications n SET state='pending',due_at=now(),updated_at=now() WHERE n.id=${notificationId} AND n.organization_id=${actor.organizationId} AND n.state='failed' AND (SELECT count(*) FROM notification_attempts a WHERE a.notification_id=n.id AND a.organization_id=n.organization_id)<${safeBound}`;return result.count===1;}
