import Link from "next/link";
import type { ReactNode } from "react";
import { sql } from "@/db/client";
import { dashboardSummary } from "@/features/dashboard/actions";
import { addDaysLocal, formatDayParam, parseDayParam, resolveScope } from "@/features/dashboard/domain";
import { SANTIAGO_TIMEZONE } from "@/features/scheduling/domain";
import { requestTenantContext } from "@/lib/request-context";
import { runAsTenant } from "@/lib/tenancy";
import { confirmDashboardAppointment,markDashboardAttendance } from "./actions";
const clp=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const dateLabel=(date:Date)=>new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(date);
const localTime=(date:Date)=>new Intl.DateTimeFormat("es-CL",{timeZone:SANTIAGO_TIMEZONE,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(date);
const statusLabel={pending:"Pendiente",confirmed:"Confirmada",cancelled:"Cancelada"};const attendanceLabel={attended:"Asistió",missed:"No asistió"};
const estimateStatusLabel:Record<string,string>={sent:"Enviado",approved:"Aprobado",draft:"Borrador",rejected:"Rechazado",expired:"Expirado"};
function Empty({children,compact=false}:{children:ReactNode;compact?:boolean}){return <p className={`state-note${compact?" state-note-compact":""}`}><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M8 12h8"/></svg>{children}</p>}
function Delta({value,fallback}:{value:number|null;fallback:string}){return <span className="metric-delta">{value===null?fallback:`${value>=0?"▲":"▼"} ${Math.abs(value)}% vs ayer`}</span>}
function Metric({label,value,sub,pct,delta,deltaFallback}:{label:string;value:string;sub:string;pct?:number|null;delta?:number|null;deltaFallback?:string}){const tone=pct==null?"":pct>=70?"success":pct>=40?"warning":"danger";return <div className="salud-item"><span>{label}</span><strong>{value}</strong>{pct!==undefined&&pct!==null?<div className="metric-bar"><i className={tone} style={{width:`${Math.min(100,pct)}%`}}/></div>:null}<small>{sub}{delta!==undefined?<> · <Delta value={delta} fallback={deltaFallback??"Aún no hay datos comparables"}/></>:null}</small></div>}
export default async function DashboardPage({searchParams}:{searchParams:Promise<{date?:string;scope?:string}>}){const params=await searchParams,actor=await requestTenantContext();let day;try{day=parseDayParam(params.date)}catch{day=parseDayParam()}const scope=resolveScope(actor,params.scope),dayValue=formatDayParam(day),boundsDate=new Date(Date.UTC(day.year,day.month-1,day.day,12));const data=await runAsTenant(sql,actor,tx=>dashboardSummary(tx,actor,day,scope));const query=(d:string,s=scope)=>`/dashboard?date=${d}&scope=${s}`;const canChoose=actor.role==="organization_admin"||actor.role==="independent_owner";const incomeSparkline=data.income?.sparkline?.slice(-7)??[];const hasIncomeSparkline=Boolean(data.income&&data.income.collectedClp>0&&incomeSparkline.some(p=>p.totalClp>0));const sparklineMax=hasIncomeSparkline?Math.max(...incomeSparkline.map(p=>p.totalClp)):1;return <main className="dashboard-page">
 <header className="dashboard-header"><div><h1>Resumen</h1><p>{dateLabel(boundsDate)}</p></div><div className="date-nav"><Link aria-label="Día anterior" href={query(formatDayParam(addDaysLocal(day,-1)))}>‹</Link><form action="/dashboard" method="get"><label className="sr-only" htmlFor="dashboard-date">Fecha</label><input id="dashboard-date" name="date" type="date" defaultValue={dayValue}/><input type="hidden" name="scope" value={scope}/><button type="submit">Ver fecha</button></form><Link aria-label="Día siguiente" href={query(formatDayParam(addDaysLocal(day,1)))}>›</Link><Link className="button" href={`/dashboard?scope=${scope}`}>Hoy</Link></div></header>
 <div className="scope-row"><div className="segmented">{canChoose?<><Link aria-current={scope==="clinic"?"page":undefined} href={query(dayValue,"clinic")}>Toda la clínica</Link><Link aria-current={scope==="own"?"page":undefined} href={query(dayValue,"own")}>Mis datos</Link></>:<span aria-current="page">{scope==="own"?"Mis datos":"Toda la clínica"}</span>}</div><p>{scope==="own"?"Solo tu actividad":"Datos de toda la clínica"}</p></div>
 <nav className="quick-access" aria-label="Accesos rápidos"><span>Accesos rápidos</span><Link href="/patients">Pacientes</Link><Link href="/estimates">Presupuestos</Link><Link href="/billing">Cobros</Link><Link href="/migration">Migración de datos</Link></nav>
 <section className="kpi-grid" aria-label="Indicadores del día"><article className="stat-card"><span className="stat-label">Citas de hoy</span><strong className="stat-value">{data.kpis.appointments}</strong><span className="stat-sub">{data.kpis.confirmed} confirmadas · {data.kpis.pending} por confirmar</span></article><article className="stat-card"><span className="stat-label">Pacientes de hoy</span><strong className="stat-value">{data.kpis.patients}</strong><span className="stat-sub">personas con cita</span></article><article className="stat-card"><span className="stat-label">Ingresos del día</span><strong className={`stat-value${data.kpis.finance&&data.kpis.finance.collectedClp>0?" accent-value":""}`}>{data.kpis.finance?clp.format(data.kpis.finance.collectedClp):"—"}</strong><span className="stat-sub">{data.kpis.finance?`${data.kpis.finance.payments} pagos registrados`:"Solo administración"}</span></article><article className="stat-card"><span className="stat-label">Sin confirmar</span><strong className={`stat-value ${data.kpis.pending?"warning-value":""}`}>{data.kpis.pending}</strong><span className="stat-sub">pendientes de confirmar hoy</span></article></section>
 <div className="dash-grid"><div className="dash-main"><section className="panel"><header className="panel-head"><h2>Agenda del día</h2><Link href={`/agenda?date=${dayValue}`}>Ver todo</Link></header><div className="panel-body">{data.agenda.length?data.agenda.map(a=><article key={a.id} className={`agenda-row ${a.status==="cancelled"?"is-cancelled":""}`}><time>{localTime(a.startsAt)}</time><div><strong>{a.patientId?<Link href={`/patients/${a.patientId}`}>{a.patientName}</Link>:a.patientName}</strong>{scope==="clinic"?<small>{a.professionalName}{a.siteName?` · ${a.siteName}`:""}</small>:null}</div><div className="agenda-chips"><span className={`chip chip-${a.status}`}>{statusLabel[a.status]}</span>{a.attendance?<span className={`chip chip-${a.attendance}`}>{attendanceLabel[a.attendance]}</span>:null}</div><div className="agenda-actions">{a.status==="pending"&&!(actor.role==="professional"&&a.professionalMembershipId!==actor.membershipId)?<form action={confirmDashboardAppointment}><input type="hidden" name="appointmentId" value={a.id}/><input type="hidden" name="date" value={dayValue}/><input type="hidden" name="scope" value={scope}/><button>Confirmar</button></form>:null}{a.status!=="cancelled"&&!(actor.role==="professional"&&a.professionalMembershipId!==actor.membershipId)?<><form action={markDashboardAttendance}><input type="hidden" name="appointmentId" value={a.id}/><input type="hidden" name="attendance" value="attended"/><button>Asistió</button></form><form action={markDashboardAttendance}><input type="hidden" name="appointmentId" value={a.id}/><input type="hidden" name="attendance" value="missed"/><button>No asistió</button></form></>:null}</div></article>):<Empty>No hay citas para este día</Empty>}</div></section>
 <section className="panel"><header className="panel-head"><h2>Salud de clínica</h2></header><div className="panel-body salud-grid"><Metric label="Ocupación" value={data.health.occupancy===null?"—":`${data.health.occupancy}%`} pct={data.health.occupancy} sub={data.health.occupancy===null?"Configura tu disponibilidad":`${(data.health.scheduledMinutes/60).toFixed(1)} h citadas de ${(data.health.capacityMinutes/60).toFixed(1)} h disponibles`}/><Metric label="Asistencia" value={data.health.attendance===null?"—":`${data.health.attendance}%`} pct={data.health.attendance} sub={data.health.marked?`${data.health.marked} de ${data.health.appointments} citas marcadas`:"Aún sin datos de asistencia"}/><Metric label="Producción" value={data.health.productionClp===null?"—":clp.format(data.health.productionClp)} sub="Cargos del día" delta={data.health.productionDelta} deltaFallback="Aún sin datos de producción"/><Metric label="Cobrado" value={data.health.collectedClp===null?"—":clp.format(data.health.collectedClp)} sub="Pagos del día" delta={data.health.collectedDelta} deltaFallback="Sin pagos este día"/><Metric label="Captación" value={String(data.health.newPatients)} sub="pacientes nuevos" delta={data.health.captureDelta} deltaFallback="Sin pacientes nuevos"/></div></section></div>
 <aside className="dash-side"><section className="panel"><header className="panel-head"><h2>Ingresos del día</h2><Link href="/billing">Ver todo</Link></header><div className="panel-body">{data.income?<><strong className={`income-total${data.income.collectedClp>0?" accent-value":""}`}>{clp.format(data.income.collectedClp)}</strong>{hasIncomeSparkline?<svg className="sparkline" viewBox="0 0 210 64" role="img" aria-label="Pagos de los últimos siete días">{incomeSparkline.map((p,i)=>{if(p.totalClp<=0)return null;const height=p.totalClp/sparklineMax*52;return <rect key={p.day} x={i*30+5} y={60-height} width="18" height={height}><title>{p.day}: {clp.format(p.totalClp)}</title></rect>})}</svg>:<Empty compact>Aún no hay pagos registrados</Empty>}{data.income.movements.length?<ul className="compact-list">{data.income.movements.map(m=><li key={m.id}><span>{localTime(m.createdAt)} · {m.patientName}</span><strong className={m.kind==="payment"?"success-text":""}>{m.kind==="payment"?"Pago":"Cargo"} · {clp.format(m.amountClp)}</strong></li>)}</ul>:hasIncomeSparkline?<Empty>Aún no hay pagos registrados</Empty>:null}</>:<Empty>Tu rol no tiene acceso a finanzas. Solicítalo al administrador</Empty>}</div></section>
 <section className="panel"><header className="panel-head"><h2>Planes de tratamiento</h2><Link href="/estimates">Ver todos</Link></header><div className="panel-body">{data.estimates?<><ul className="compact-list">{[["sent","Enviados"],["approved","Aprobados"],["draft","Borradores"],["rejected","Rechazados"],["expired","Expirados"]].map(([key,label])=><li key={key}><span>{label}</span><strong>{data.estimates!.states[key].count}{key!=="draft"?` · ${clp.format(data.estimates!.states[key].totalClp)}`:""}</strong></li>)}</ul>{data.estimates.recent.slice(0,3).map(e=><p key={e.id}><Link href="/estimates">{e.patientName}</Link> · {estimateStatusLabel[e.state]}</p>)}</>:<Empty>Tu rol no tiene acceso a planes de tratamiento</Empty>}</div></section>
 <section className="panel"><header className="panel-head"><h2>Evoluciones pendientes</h2></header><div className="panel-body">{data.pendingClinical?<><div className="pending-counts"><strong>Hoy: {data.pendingClinical.today}</strong><strong>Total: {data.pendingClinical.total}</strong></div>{data.pendingClinical.recent.slice(0,3).map(e=><p key={`${e.patientId}-${e.startsAt.toISOString()}`}><Link href={`/patients/${e.patientId}`}>{e.patientName}</Link><small>{dateLabel(e.startsAt)}</small></p>)}<p className="muted">Evolución = nota clínica tras la atención</p></>:<Empty>Tu rol no tiene acceso a evoluciones clínicas</Empty>}</div></section></aside></div>
 </main>}
